<a href="https://colab.research.google.com/github/LokeCoder11/KnowledgeReference/blob/main/GEN_AI_Session_April_20_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# History of Gen AI with example
- What is NLP
- what application we use to solve in NLP
- how algo is developed from basic model to LM and then to LLM

- NLP : Natural Language processing (Domain under data science)
 - Machine learning (Domian under data science)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel(r"C:\Users\Lenovo\OneDrive\Desktop\New Microsoft Excel Worksheet.xlsx")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df["Message"][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

- Can we solve this using Machine learning directly

In [ ]:
# can you directly utilize this data -- No?

In [ ]:
df["Message"] = df["Message"].astype(str).str.lower()
df.head(2)

Category                                            Message
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...

In [ ]:
s1 = ['hi how are you','I am good']
s1 = " ".join(s1)
s1 = s1.split(" ")
s1

['hi', 'how', 'are', 'you', 'I', 'am', 'good']

In [ ]:
vocab = set(s1)
vocab

{'I', 'am', 'are', 'good', 'hi', 'how', 'you'}

In [ ]:
s1 = ['hi how are you',
      'I am good']
conversion = []
for k in s1:
    emp = []
    #print(k)
    for i in vocab:
        if i in k:
            emp.append(1)
        else:
            emp.append(0)
    conversion.append(emp)

In [ ]:
conversion

[[0, 1, 1, 1, 0, 1, 0], [1, 0, 0, 0, 1, 0, 1]]

# converted the text data into binary 1/0 format using vocab method - this is called BAG OF WORD METHOD

In [ ]:
conversion

[[0, 1, 1, 1, 0, 1, 0], [1, 0, 0, 0, 1, 0, 1]]

In [ ]:
from sklearn.feature_extraction import text
print(dir(text))

['BaseEstimator', 'CountVectorizer', 'ENGLISH_STOP_WORDS', 'FLOAT_DTYPES', 'FeatureHasher', 'HasMethods', 'HashingVectorizer', 'Integral', 'Interval', 'Mapping', 'NotFittedError', 'OneToOneFeatureMixin', 'Real', 'StrOptions', 'TfidfTransformer', 'TfidfVectorizer', 'TransformerMixin', '_IS_32BIT', '_VectorizerMixin', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_analyze', '_check_stop_list', '_document_frequency', '_make_int_array', '_preprocess', 'array', 'check_array', 'check_is_fitted', 'defaultdict', 'itemgetter', 'normalize', 'np', 'partial', 're', 'sp', 'strip_accents_ascii', 'strip_accents_unicode', 'strip_tags', 'unicodedata', 'warnings']


In [ ]:
from sklearn import *
import sklearn
print(dir(sklearn))

['__SKLEARN_SETUP__', '__all__', '__builtins__', '__cached__', '__check_build', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_distributor_init', '_isotonic', '_loss', 'base', 'calibration', 'clone', 'cluster', 'compose', 'config_context', 'covariance', 'cross_decomposition', 'datasets', 'decomposition', 'discriminant_analysis', 'dummy', 'ensemble', 'exceptions', 'experimental', 'externals', 'feature_extraction', 'feature_selection', 'gaussian_process', 'get_config', 'impute', 'inspection', 'isotonic', 'kernel_approximation', 'kernel_ridge', 'linear_model', 'logger', 'logging', 'manifold', 'metrics', 'mixture', 'model_selection', 'multiclass', 'multioutput', 'naive_bayes', 'neighbors', 'neural_network', 'os', 'pipeline', 'preprocessing', 'random', 'random_projection', 'semi_supervised', 'set_config', 'setup_module', 'show_versions', 'svm', 'sys', 'tree', 'utils']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
?cv

In [ ]:
df1 = pd.DataFrame({"mess":['This is the first document.','This document is the second document.','And this is the third one.',
                            'Is this the first document?']})
df1

mess
0            This is the first document.
1  This document is the second document.
2             And this is the third one.
3            Is this the first document?

In [ ]:
v1 = [i for i in df1["mess"]]
v1 = " ".join(v1)
V1 = v1.split(" ")
print(V1)

['This', 'is', 'the', 'first', 'document.', 'This', 'document', 'is', 'the', 'second', 'document.', 'And', 'this', 'is', 'the', 'third', 'one.', 'Is', 'this', 'the', 'first', 'document?']


In [ ]:
len(set(V1))

13

In [ ]:
print(set(V1))

{'document.', 'third', 'is', 'And', 'document', 'Is', 'one.', 'first', 'document?', 'this', 'This', 'the', 'second'}


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
tfidf  = TfidfVectorizer()
X = cv.fit_transform(df1["mess"])
X1 = tfidf.fit_transform(df1["mess"])

In [ ]:
df1

mess
0            This is the first document.
1  This document is the second document.
2             And this is the third one.
3            Is this the first document?

In [ ]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [ ]:
X1.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [ ]:
X2 = X.toarray()
len(X2[0])

9

- I am showing very limited type of methods there are a lot of method which you can explore


In [ ]:
df = pd.read_excel(r"C:\Users\Lenovo\OneDrive\Desktop\New Microsoft Excel Worksheet.xlsx")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df["Message"] = df["Message"].astype(str).str.lower()
df.head(2)
# regex function (regular expression) -people in web extarction (scrap website) - data

Category                                            Message
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...

In [ ]:
import re
p= "noida"
text = "I see people in noida who are enganged in labour job, but compare to newyork noida is not that bad"
re.findall(p,text)

['noida', 'noida']

In [ ]:
X = cv.fit_transform(df["Message"])
Y = np.where(df["Category"]=='ham',0,1)

In [ ]:
X

<5572x8674 sparse matrix of type '<class 'numpy.int64'>'
	with 73917 stored elements in Compressed Sparse Row format>

In [ ]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
Y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
pred = model.predict(x_test)
pred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
my_message = 'you won a lottery of 25000$ call me to take the money'

In [ ]:
conv_messg = cv.transform(['you won a lottery of 25000$ call me to take the money'])
conv_messg

<1x8674 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [ ]:
conv_messg.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
pre_me = model.predict(conv_messg)
pre_me

array([0])

application 2: Instead of having the message take the reviews of resturant
              data(reviews)                                 Tag
1) food was good and service was fast                  positive
2) food quality was ok and 1 time you can visit        Neutral
3) very bad i will not go                              Negative

- if a company can use NLP to create a classification model which can provide the respose from use whether it is pos/neg/neu can help the company to understand weakness

In [ ]:
s1 =["pepsi 1 lt",'iphone 15','pepsi 750 ml']
# which two product belongs to same brand

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
tfidf  = TfidfVectorizer()

In [ ]:
v = tfidf.fit_transform(s1)
v.toarray()

array([[0.        , 0.        , 0.        , 0.79596054, 0.        ,
        0.60534851],
       [0.70710678, 0.        , 0.70710678, 0.        , 0.        ,
        0.        ],
       [0.        , 0.62276601, 0.        , 0.        , 0.62276601,
        0.4736296 ]])

In [ ]:
v.toarray()[0]

array([0.        , 0.        , 0.        , 0.79596054, 0.        ,
       0.60534851])

In [ ]:
v.toarray()[1]

array([0.70710678, 0.        , 0.70710678, 0.        , 0.        ,
       0.        ])

- cosin similarity - method which tell how close or similar two vector are

In [ ]:
from sklearn.metrics import  pairwise_distances
print(dir(metrics))

['ConfusionMatrixDisplay', 'DetCurveDisplay', 'DistanceMetric', 'PrecisionRecallDisplay', 'PredictionErrorDisplay', 'RocCurveDisplay', 'SCORERS', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_classification', '_dist_metrics', '_pairwise_distances_reduction', '_pairwise_fast', '_plot', '_ranking', '_regression', '_scorer', 'accuracy_score', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'auc', 'average_precision_score', 'balanced_accuracy_score', 'brier_score_loss', 'calinski_harabasz_score', 'check_scoring', 'class_likelihood_ratios', 'classification_report', 'cluster', 'cohen_kappa_score', 'completeness_score', 'confusion_matrix', 'consensus_score', 'coverage_error', 'd2_absolute_error_score', 'd2_pinball_score', 'd2_tweedie_score', 'davies_bouldin_score', 'dcg_score', 'det_curve', 'euclidean_distances', 'explained_variance_score', 'f1_score', 'fbeta_score', 'fowlkes_mallows_score', 'ge

In [ ]:
s1

['pepsi 1 lt', 'iphone 15', 'pepsi 750 ml']

In [ ]:
pairwise_distances([v.toarray()[0]],[v.toarray()[1]])

array([[1.41421356]])

In [ ]:
pairwise_distances([v.toarray()[0]],[v.toarray()[2]])

array([[1.19439443]])

# retail & CPG
- ecomm website

In [ ]:
import pandas as pd